### ISSUE TITLE
Add tests scenarios for adding password

### ISSUE THREAD

**Issue by lpegoraro** [lpegoraro/password-manager#30]
Add unit tests of the following methods:
password-manager/password_manager.go
- func parseArgs(arguments []string)
  - To cover the if and entry to handleAdd
- func handleAdd(arguments []string)
- func AddPassword(description, username string, overrideConfig PasswordConfiguration) string

**Comment by fortrieb** [comment]
Hi @lpegoraro 
i will take this issue if nobody else is already working on it.

**Comment by lpegoraro** [comment]
@fortrieb feel free, you are the first.
